---
- name: Install Docker using command line
  hosts: servers
  become: yes

  tasks:
    - name: Update apt package index
      command: apt-get update

#    - name: Install dependencies
#      command: apt-get install -y apt-transport-https ca-certificates curl software-properties-common

#    - name: Add Docker GPG key
#    command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

#    - name: Add Docker repository
#      command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Update apt package index again
      command: apt-get update

#    - name: Install Docker
#      command: apt-get install -y docker-ce

    - name: Start and enable Docker
      command: systemctl enable --now docker

